### PR TITLE
Deepak | Tic Tac Toe

### PR DESCRIPTION
**Pull request by Deepakv14**
Added few Changes

### Track

- [ ] Android
- [ ] Flutter
- [ ] Web Devlopment

#### Tic Tac Toe

- [ ] **Task 1**: Implement a two-player mode that allows two people to compete against each other.
- [ ] **Task 2**: Add a single-player mode that allows users to play with an intelligent bot that never loses.
- [ ] **Task 3**: Add an option to select which shape to begin with (X/O).
- [ ] **Task 4:** In single-player mode, add an option to choose who will start first - computer or player.
- [ ] **Extras:** You may keep a record of scores and use player names for interactivity.

#### Sudoku

- [ ] **Task 1**: Implement a Sudoku game. (The board may remain the same every time).
- [ ] **Task 2**: Implement a board generator and generate a random board in every game. You may use backtracking or naive approaches to generate the board.
- [ ] **Task 3:** Add a timer to the game, where the user may select a particular time to complete the game within it. **Bonus**: As the time reaches 0, the user can be warned about the time running out.
- [ ] **Task 4:** Warning the user about incorrect inputs and user engagement.
- [ ] **Extras:** To make the game more engaging, you may provide hints if the user is stuck for like 10-20 seconds.

### Submission

Deepak Verma - [github Repo](https://github.com/Deepakv14/TicTacToeFinal.github.io) [Web Site](https://deepakv14.github.io/TicTacToeFinal.github.io/)

### CODE REVIEW

**Comment by m-e-l-u-h-a-n** [comment]
Hey, you haven't added the link to the GitHub repo for your code, as a result, we are not able to judge your submission from a code perspective. Can you please update it by evening?

**Comment by Deepakv14** [comment]
> Hey, you haven't added the link to the GitHub repo for your code, as a result, we are not able to judge your submission from a code perspective. Can you please update it by evening?

Bhaiyya I have added ...... web site and Github repo both on same line....see at the bottom

**Comment by m-e-l-u-h-a-n** [comment]
image

But they both are pointing to the same URL (deployed link). In case you have some doubt your repo URL will be like:
```
https://github.com/Deepakv14/your-repo-name/
```

**Comment by shubhanshu02** [comment]
Hi @Deepakv14! Kudos for completing the task. Here are a few suggestions I'd like to share:

1. The single-player mode doesn't seem to work at all (I couldn't even find any function regarding it in your source code). If you are not able to implement the minimax algorithm, you can have an AI agent that marks the first empty box with its marker as a simple solution (Though the minimax approach would result in a much smarter AI).
2. Styling may be improved for an engaging experience and add some title for the HTML document.
3. You can have the human player choose the marker instead of using 'O' by default.

Still it was a good try. Congratulations :+1:

**Pull request merged**
