### PR TITLE
Added name, repo name and site-link

### PR DESCRIPTION
**Pull request by aditya-chhaparia**
### Track

- [ ] Android
- [ ] Flutter
- [x] Web Devlopment

#### Tic Tac Toe

- [ ] **Task 1**: Implement a two-player mode that allows two people to compete against each other.
- [ ] **Task 2**: Add a single-player mode that allows users to play with an intelligent bot that never loses.
- [ ] **Task 3**: Add an option to select which shape to begin with (X/O).
- [ ] **Task 4:** In single-player mode, add an option to choose who will start first - computer or player.
- [ ] **Extras:** You may keep a record of scores and use player names for interactivity.

#### Sudoku

- [x] **Task 1**: Implement a Sudoku game. (The board may remain the same every time).
- [x] **Task 2**: Implement a board generator and generate a random board in every game. You may use backtracking or naive approaches to generate the board.
- [x] **Task 3:** Add a timer to the game, where the user may select a particular time to complete the game within it. **Bonus**: As the time reaches 0, the user can be warned about the time running out.
- [x] **Task 4:** Warning the user about incorrect inputs and user engagement.
- [ ] **Extras:** To make the game more engaging, you may provide hints if the user is stuck for like 10-20 seconds.

### Submission

[Repo](https://github.com/aditya-chhaparia/csoc-2021-task-1)
[Web Site](https://aditya-chhaparia.github.io/sudoku-game/)

### CODE REVIEW

**Comment by king-11** [comment]
Please remove the unnecessary tab vs space changes that you have made and also fill in the template :)

**Comment by king-11** [comment]
You weren't supposed to update the PR template 😅 just add in your data in the description as per template

**Comment by aditya-chhaparia** [comment]
I realized that and i reversed those changes.

**Comment by shubhanshu02** [comment]
Hi @aditya-chhaparia! Kudos for completing the task. Here are a few suggestions I'd like to share:

1. After the timer runs out, you can show a solution to that sudoku board.
2. The UI looks clean but can be improved to make the game engaging.
3. You can also change the color of the timer as time progresses to catch the attention of the user.

Overall, it was a good try. Congratulations :+1:

**Comment by aditya-chhaparia** [comment]
> Hi @aditya-chhaparia! Kudos for completing the task. Here are a few suggestions I'd like to share:
> 
> 1. After the timer runs out, you can show a solution to that sudoku board.
> 2. The UI looks clean but can be improved to make the game engaging.
> 3. You can also change the color of the timer as time progresses to catch the attention of the user.
> 
> Overall, it was a good try. Congratulations

@shubhanshu02 
It already displays the solution when the timer runs
Screenshot from 2021-06-25 05-43-20

**Comment by shubhanshu02** [comment]
> @shubhanshu02 It already displays the solution when the timer runs

Oh, my mistake then. Corrected!

**Pull request merged**
