### PR TITLE
Chirayu_Mittal_Tic_Tac_Toe

### PR DESCRIPTION
**Pull request by chirayumit001**
### Track

- [ ] Android
- [x] Flutter
- [ ] Web Devlopment

#### Tic Tac Toe

- [x] **Task 1**: Implement a two-player mode that allows two people to compete against each other.
- [x] **Task 2**: Add a single-player mode that allows users to play with an intelligent bot that never loses.
- [x] **Task 3**: Add an option to select which shape to begin with (X/O).
- [x] **Task 4:** In single-player mode, add an option to choose who will start first - computer or player.
- [x] **Extras:** You may keep a record of scores and use player names for interactivity.

#### Sudoku

- [ ] **Task 1**: Implement a Sudoku game. (The board may remain the same every time).
- [ ] **Task 2**: Implement a board generator and generate a random board in every game. You may use backtracking or naive approaches to generate the board.
- [ ] **Task 3:** Add a timer to the game, where the user may select a particular time to complete the game within it. **Bonus**: As the time reaches 0, the user can be warned about the time running out.
- [ ] **Task 4:** Warning the user about incorrect inputs and user engagement.
- [ ] **Extras:** To make the game more engaging, you may provide hints if the user is stuck for like 10-20 seconds.

### Submission

[tic-tac-toe_Chirayu](https://github.com/chirayumit001/csoc-2021-task-1.git)
[APK|Web Site](https://mine-tic-tac-toe-game.netlify.app/#/)

### CODE REVIEW

**Comment by nb9960** [comment]
Nice work @chirayumit001. Just a few suggestions for improvement:
- You entered hardcoded height and width for the board container because of which board wasn't responsive.
- UI could have been better
- It was clearly mentioned in the PS that in single-player mode bot should always go for the winning move but you randomly choose a box in AI's turn.
- If all boxes are filled and a player wins then both draw dialog and win dialog pops up and the winner's score is incremented by 2. This shouldn't be the case. This due to the draw condition you have put under `_checkWinner` function
Your submission is evaluated and scores would be communicated soon.

**Comment by chirayumit001** [comment]
Hello di!!!
Thank you for your response.
For AI only choses randomly when selected easy mode, if selected difficult mode then it will always win.
There is an option given in the UI to select difficulty level.

**Comment by chirayumit001** [comment]
ui

**Comment by nb9960** [comment]
@chirayumit001 Didn't noticed that. Updated the score accordingly. Thanks for informing!

**Pull request merged**
