### PR TITLE
Created Sudoku-Game

### PR DESCRIPTION
**Pull request by tiger-yash**
### Track

- [ ] Android
- [ ] Flutter
- [x] Web Devlopment

#### Tic Tac Toe

- [ ] **Task 1**: Implement a two-player mode that allows two people to compete against each other.
- [ ] **Task 2**: Add a single-player mode that allows users to play with an intelligent bot that never loses.
- [ ] **Task 3**: Add an option to select which shape to begin with (X/O).
- [ ] **Task 4:** In single-player mode, add an option to choose who will start first - computer or player.
- [ ] **Extras:** You may keep a record of scores and use player names for interactivity.

#### Sudoku

- [x] **Task 1**: Implement a Sudoku game. (The board may remain the same every time).
- [x] **Task 2**: Implement a board generator and generate a random board in every game. You may use backtracking or naive approaches to generate the board.
- [x] **Task 3:** Add a timer to the game, where the user may select a particular time to complete the game within it. **Bonus**: As the time reaches 0, the user can be warned about the time running out.
- [x] **Task 4:** Warning the user about incorrect inputs and user engagement.
- [x] **Extras:** To make the game more engaging, you may provide hints if the user is stuck for like 10-20 seconds.

### Submission

[Repo](https://github.com/tiger-yash/Sudoku-Game)
[APK|Web Site](https://tiger-yash.github.io/Sudoku-Game/)

### CODE REVIEW

**Comment by aditya-chhaparia** [comment]
The sudokus your program generates are not necessarily uniquely solvable. The java code on the geeksforgeeks website was flawed.
Screenshot from 2021-06-13 07-52-26
I added some code to print all solutions to the java code from the website.

**Comment by tiger-yash** [comment]
> The sudokus your program generates are not necessarily uniquely solvable. The java code on the geeksforgeeks website was flawed.
> Screenshot from 2021-06-13 07-52-26
> I added some code to print all solutions to the java code from the website.

Thank You for Informing! 
I Have now fixed that bug to make the game more flexible and to accept any solution the user has to provide.

**Comment by tiger-yash** [comment]
Thank You for Informing!
I Have now fixed that bug to make the game more flexible and to accept any solution the user has to provide.

**Comment by shubhanshu02** [comment]
Hi @tiger-yash, I reviewed your submission, and here are a few suggestions I'd like to share:

1. It was great to show instructions on the game, but the styling of the box can be slightly improved.
2. The UI is engaging and responsive as well. Good work on that :1st_place_medal: 
3. The hints feature works fine.
4. The dropdowns in the navbar (for mobile screens) can be a bit wider for a better look.
5. After the time's up, you can display a solution to the board.

Overall, it was a great try. Congratulations :+1:

**Comment by tiger-yash** [comment]
Thank You @shubhanshu02 Sir! 
I will keep everything you suggested in mind and try to implement it and I hope to keep learning more under your expertise.

*Also, for the Solution after time's up(5th pt.) :  I provided the Solve Button which gets activated automatically after Half the time is over (as mentioned in the instructions), so that the user can himself choose to view the solution.

**Pull request merged**
